### ISSUE TITLE
no FG server found

### ISSUE THREAD

**Issue by mattcheerio** [notatallshaw/fall_guys_ping_estimate#51] opened 2022-01-24 14:32 UTC
Hello,
I didnt know how to contact you in other way. It only says Looking for FG server and then nothing ever happens.
Is this app still compatible with epic servers?? I'd really like to use your app!!
Can u help me out? Im on W11
Cheers Matt

**Comment by notatallshaw** [comment] 2022-01-24 14:36
Hi Matt,

Are you using the latest version of the tool? https://github.com/notatallshaw/fall_guys_ping_estimate/releases/download/latest/run_fgpe.exe

There was an issue in season 6 where Fall Guys started writing non-Unicode characters to the logs and I had to update the code to handle this.

Damian

**Comment by mattcheerio** [comment] 2022-01-24 14:37
I will post you any details of your Report Unknown Region / Location topic later as im not home atm

**Comment by notatallshaw** [comment] 2022-01-24 14:41
In that case when you get a chance:

1. Open File Explorer
2. Paste this in to the address and hit enter: `%APPDATA%\fgpe`
3. Drag and drop all the files in to this issue




> Also, defender is giving me a hard time

Yes, not a lot I can do about this. Sometimes defender acts up and starts deleting the file. I've not seen this in many months but if it happens I don't have any solution other than adding it in to an exclusion list.

**Comment by notatallshaw** [comment] 2022-01-24 14:44
> I will post you any details of your Report Unknown Region / Location topic later as im not home atm if that helps! 

FYI the latest version of the tool doesn't show "Unknown" any more, in the cases it doesn't know the server it shows the IP address of the server.

**Comment by mattcheerio** [comment] 2022-01-24 14:51
> > I will post you any details of your Report Unknown Region / Location topic later as im not home atm if that helps!
> 
> FYI the latest version of the tool doesn't show "Unknown" any more, in the cases it doesn't know the server it shows the IP address of the server.

Im only playing on Europe, but the tool didnt show any IP address. it registered that i started the game though, as it was saying FG not running at the start

**Comment by notatallshaw** [comment] 2022-01-24 15:00
Once you get home send me the logs. One final question, when did this start happening?

**Comment by mattcheerio** [comment] 2022-01-24 15:03
>>One final question, when did this start happening?

what u mean exactly? im new to your tool, just started today

**Comment by mattcheerio** [comment] 2022-01-24 15:06
>Once you get home send me the files. 

Will do so!! For sure, thanks for helpin !!

**Comment by notatallshaw** [comment] 2022-01-24 15:20
> > Once you get home send me the files.
> 
> Will do so!! For sure, thanks for helpin !!

Great, also send me a screenshot of what the problem looks like if you can.

There are 2 likely outcomes to this:

1. I'll immediately know what the problem is and be able to fix the issue straight away
2. I will have no idea what the problem is and I may make a new version of the tool just to give better logging for you to run and then send me the new logging.

**Comment by mattcheerio** [comment] 2022-01-24 16:24
[stats.csv](https://github.com/notatallshaw/fall_guys_ping_estimate/files/7927103/stats.csv)
[unknown_ip_addresses.csv](https://github.com/notatallshaw/fall_guys_ping_estimate/files/7927104/unknown_ip_addresses.csv)
[Fall_Guys_IP_Networks.csv](https://github.com/notatallshaw/fall_guys_ping_estimate/files/7927105/Fall_Guys_IP_Networks.csv)

**Comment by mattcheerio** [comment] 2022-01-24 16:30
![Screenshot 2022-01-24 172635](https://user-images.githubusercontent.com/98331096/150823636-d41af7e3-a748-46f8-ba1d-cdd8f5363263.png)
![Screenshot 2022-01-24 172647](https://user-images.githubusercontent.com/98331096/150823642-cd5a925c-bf37-49f2-bf69-20e8c79abf5b.png)
![Screenshot 2022-01-24 172805](https://user-images.githubusercontent.com/98331096/150823648-7267da9f-89ac-43cf-901e-56e3f0b38121.png)
![Screenshot 2022-01-24 172910](https://user-images.githubusercontent.com/98331096/150823653-d02794da-d085-494b-88ba-a363c6899d94.png)

**Comment by notatallshaw** [comment] 2022-01-24 16:56
Thanks!

It looks like something caused the code internally to crash so it gets stuck frozen on "Not Connected to Fall Guys Server".

I am going to need to make a new version of the tool that logs the crash so I know what happened.

Give me a day or two and I'll get back to you with a new version.

**Comment by mattcheerio** [comment] 2022-01-24 17:08
Ohhh, that would be suuuper nice of you if u can manage sth for me out!! Thanks a lot!

**Comment by notatallshaw** [comment] 2022-03-14 01:01
Hey sorry I never replied, lots of real life stuff came up.

Should be fixed with the latest release (just published): https://github.com/notatallshaw/fall_guys_ping_estimate/releases/download/latest/run_fgpe.exe

**Comment by notatallshaw** [comment] 2022-03-14 14:04
I'm going to close this issue for now as I'm 98% confident it was fixed in the latest release. But you will still be able to reply and I can reopen this issue if it is still ongoing.

**Closed by notatallshaw** 2022-03-14 14:04 UTC
